-- Natural Records Community — Supabase setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.community_messages (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.community_messages enable row level security;

-- Anyone can read the community feed. Only authenticated users can post.
drop policy if exists "Anyone can read community messages" on public.community_messages;
create policy "Anyone can read community messages"
on public.community_messages for select
using (true);

drop policy if exists "Authenticated users can post" on public.community_messages;
create policy "Authenticated users can post"
on public.community_messages for insert
to authenticated
with check (auth.uid() = author_id);

drop policy if exists "Users can delete their own messages" on public.community_messages;
create policy "Users can delete their own messages"
on public.community_messages for delete
to authenticated
using (auth.uid() = author_id);

-- Always derive the displayed author name from the authenticated account.
-- The browser cannot choose another user's name.
create or replace function public.set_community_author_name()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  account_name text;
begin
  select coalesce(
    nullif(trim(raw_user_meta_data ->> 'display_name'), ''),
    nullif(trim(raw_user_meta_data ->> 'full_name'), ''),
    nullif(split_part(email, '@', 1), '')
  )
  into account_name
  from auth.users
  where id = new.author_id;

  new.author_name := coalesce(account_name, 'Anonymous');
  return new;
end;
$$;

drop trigger if exists community_author_name on public.community_messages;
create trigger community_author_name
before insert on public.community_messages
for each row execute function public.set_community_author_name();

create index if not exists community_messages_created_at_idx
on public.community_messages (created_at desc);
